### ISSUE TITLE
Help in running code 

### ISSUE THREAD

**Issue by Rabia-Raja** [JordiCorbilla/stock-prediction-deep-neural-learning#1]
Hi. Can  I run this code on our own dataset

**Comment by JordiCorbilla** [comment]
Hi @Rabia-Raja sure you can. Just send your dataset in and it should work.

**Comment by Rabia-Raja** [comment]
But your code seems very complex. I  tried to understand where I can fix my
.csv file but seriously I did not get any idea. Can you please help me
regarding data fitting

**Comment by JordiCorbilla** [comment]
@Rabia-Raja sorry for my late reply, do you still need help here?
