### ISSUE TITLE
I also did this project 3 years ago. I have a question for your project

### ISSUE THREAD

**Issue by appydam** [JordiCorbilla/stock-prediction-deep-neural-learning#13]
in section 3.5

there are 2 color lines representing actual and predicted.

can you also show the next month prediction graph and how accurate is that

**Comment by JordiCorbilla** [comment]
In a time series prediction scenario, adding a month in advance to the prediction graph `doesn't inherently make sense` for assessing accuracy. The accuracy of my LSTM (Long Short-Term Memory) model is typically evaluated based on how well it predicts values at each time step in the future (by default 3 days).

**Comment by appydam** [comment]
Have you done for next 3 days?
I can't see it.
Can you share that here?

**Comment by JordiCorbilla** [comment]
I've updated the notebook to include the inference part, you can check it out there. 
https://github.com/JordiCorbilla/stock-prediction-deep-neural-learning/blob/master/stock_prediction_lstm.ipynb
![image](https://github.com/JordiCorbilla/stock-prediction-deep-neural-learning/assets/7347994/f0943261-8669-4150-9c75-7263c23c0fe3)
