### ISSUE TITLE
How to forecast the next nth price

### ISSUE THREAD

**Issue by vinc1am** [JordiCorbilla/stock-prediction-deep-neural-learning#15]
Thanks for sharing the insight and code. May I know is it possible to predict multiple days ahead using the model? From the model architecture the model can only return 1 day ahead of the forecast. I have tried to use your model to iterate the model inferencing of the predicted value as input, but the result is not that good. Could you give me some advice for this? Many thanks.

**Comment by JordiCorbilla** [comment]
have you tried the example from my notebook?
https://github.com/JordiCorbilla/stock-prediction-deep-neural-learning/blob/master/stock_prediction_lstm.ipynb
