### ISSUE TITLE
Am I looking at it wrong or is the "prediction" simply a time delayed noisy copy of the input sequence?

### ISSUE THREAD

**Issue by donjonson** [JordiCorbilla/stock-prediction-deep-neural-learning#2]
I have not looked through the project yet but it seems like you went through an extremely complex method just to generate a poor quality time delayed duplicate of the input?

I am not critical I am just trying to understand what I am seeing?

**Comment by JordiCorbilla** [comment]
Hi @donjonson, 
The idea here is to use deep learning to predict a certain value in the future. So whatever you are seeing in the output is part of a decision made by the network which is in line with the market trend and with very little error (MSE (Mean Square Error) of 0.14%). This might seem overly complicated but it's a good way to build a history on previous values (given a time window to inspect) and then see a prediction given by the model.
