### ISSUE TITLE
Herramienta complementaria 

### ISSUE THREAD

**Issue by Leci37** [JordiCorbilla/stock-prediction-deep-neural-learning#7]
Me llamo Luis, soy desarrollador big-data machine-learning, soy un fan de tu trabajo, y suelo fijarme en tus actualizaciones.

Temeroso que mis ahorros se los comiera la inflación. He creado una potente herramienta que en función de los patrones técnicos pasados (volatilidad, medias móviles, estadísticos,tendencias, velas, soportes y resistencias, indicadores de índice bursátil).
Todos los que conoces (RSI, MACD, STOCH, Bolinger Bands, SMA, DEMARK, velas japonesas, ichimoku, fibonacci, williansR, balance of power, murrey math) y más de 200 más
 
La herramienta crea modelos de predicción de puntos de **operativa correctos** (donde comprar y dónde vender, toda acción es buena operada a tiempo y dirección)
Para ellos me he ayudado de herramientas big data como pandas python , librerías bursátiles como: tablib, TAcharts ,pandas_ta… Para la recogida y cálculo de los datos. 
Y de potentes librerías  machine-learning como: Sklearn.RandomForest ,  Sklearn.GradientBoosting, XGBoost, Google TensorFlow y Google TensorFlow LSTM.
 
Con los modelos entrenados con la selección de mejores indicadores técnicos, la herramienta es capaz de predecir puntos de operativa (donde comprar , donde vender) y mandar alerta en tiempo real al Telegram o Mail. Los puntos son calculados en función del aprendizaje de los puntos de operativa correctos de los últimos 2 años  (incluyendo el cambio a mercado bajista tras la subida de tipos) 
 
Creo que te podría ser útil, para mejorar, me gustaría cedertela, y si estás interesado en mejorar  y colaborar también estoy dispuesto, y si no archivarla en el cajón

**Comment by JordiCorbilla** [comment]
Gracias @Leci37! me parace muy interesante tu herramienta!
Dime como podemos colaborar y mejorarla!

**Comment by JordiCorbilla** [comment]
Muy buen documento @Leci37! gracias!!

**Comment by Leci37** [comment]
Ya te lo he compartido. no sé si le has podido echar un ojo

**Comment by flower-lu** [comment]
I will check it later.Thank you , bro.



---Original---
From: "Luis ***@***.***&gt;
Date: Sun, Nov 13, 2022 18:34 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [JordiCorbilla/stock-prediction-deep-neural-learning] Herramientacomplementaria  (Issue #7)




 
Ya te lo he compartido. no sé si le has podido echar un ojo

**Comment by JordiCorbilla** [comment]
Si @Leci37 muy buen documento y tambien lo que has construido. dime que quieres hacer next

**Comment by Leci37** [comment]
Me alegro que te haya gustado,
Lo he estado probando en tiempo real, y funciona.
Pero yo creo que se prodria mejorar bastante el rendimiento usando arrays multidimensionales , es decir, ahora se usan (n) columnas , yo quiero n columnas más 8 o 10 en el pasado inmediato , un array de  (n x 8) ventanas los llama google (https://www.tensorflow.org/tutorials/structured_data/time_series )
Esto esta medio hecho , consigo los arrays multidimensionales, pero no que entrene TF (conv1, LSTM ...)  con ellos 


Para ello esta este punto en documentación Mejoras en los modelos predictivos, usando multidimensionales
![image](https://user-images.githubusercontent.com/110530848/201532213-f2349dbe-2bda-4172-a01a-8a1d5aee5703.png)

Cualquier duda dime 
¿como crees que se podria mejorar ?

**Comment by Leci37** [comment]
![image](https://user-images.githubusercontent.com/110530848/201533543-be5f28cd-baf7-471b-8b62-fc39ace5ad2f.png)
Meterle esto , q evalue , LTSM , conv2 y conv1 , y 3-4 más,  en multidimensional
