### ISSUE TITLE
How can we use this to predict future dates (outside training/validation)?

### ISSUE THREAD

**Issue by whoopydev** [JordiCorbilla/stock-prediction-deep-neural-learning#8]
Hey, 

First, I want to thank you for creating this amazing project. This has been of great help in helping me learn time series forecasting. 

I have successfully been able to train and predict validation data with the model, however I'd like to know how I can predict future dates outside the test data. 

I tried running the `stock_prediction_deep_learning_inference.py` script, however that fails to work. 

EDIT: To be more specific, it doesn't work because of missing arguements. Eg: `TypeError: StockPrediction.__init__() missing 5 required positional arguments: 'github_url', 'epochs', 'time_steps', 'token', and 'batch_size'`

Any help would be appreciated, 
Thanks!

**Comment by whoopydev** [comment]
Never mind, I got this to work. I just added the missing args from the jupyter file.

**Comment by JordiCorbilla** [comment]
Excellent!
