### ISSUE TITLE
Why does each run of inference produce different results?

### ISSUE THREAD

**Issue by joeystevens00** [JordiCorbilla/stock-prediction-deep-neural-learning#9]
I tried training the LSTM network using ticker data for  DX-Y.NYB with data going back to 1968 and validation data going back 2 years. The rest of the inputs I left at default values only changing ticker, start date, and validation date. Using this model I ran predictions a few times but each time got wildly different results. It doesn't really seem like the model has any confidence in its predictions if each run produces a completely different outcome. Are there some tweaks I should make to the settings to produce better results?

**Comment by JordiCorbilla** [comment]
could be because the model might not be able to find a prediction. you could try changing the window for the ltsm algo so it looks at a smaller one.
